name: geoforestcoletor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  # =============================================================
  # =================== MUDANÇA IMPORTANTE AQUI ===================
  # Usando uma faixa de versão mais comum e flexível para o SDK
  # =============================================================
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Pacotes Essenciais ---
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  intl: ^0.18.1
  sqflite: ^2.3.2
  path: ^1.9.0
  geolocator: ^11.1.0
  csv: ^6.0.0
  path_provider: ^2.1.3
  share_plus: ^8.0.2
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.1.0
  url_launcher: ^6.2.6
  permission_handler: ^11.3.1
  provider: ^6.0.4


  # --- Pacotes do Mapa e Geometria ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  file_picker: ^8.2.0 # Versão mais recente
  shapefile: ^1.0.1
  flutter_speed_dial: ^7.0.0
  proj4dart: ^2.1.0
  
  

  # --- Pacotes Desktop ---
  sqflite_common_ffi: ^2.3.3
  
dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Versão mais comum é ^3.0.0 ou ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_2.png