// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsg5PMINPmDNg4GYWv9ZS6tckckZBM8so',
    appId: '1:42806286143:web:b566c9d8f7a7da89afe58a',
    messagingSenderId: '42806286143',
    projectId: 'coletorgeoforest',
    authDomain: 'coletorgeoforest.firebaseapp.com',
    storageBucket: 'coletorgeoforest.firebasestorage.app',
    measurementId: 'G-2SGP5N7HWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu6KQNjeu1ZDD3-yi4yjXr1T9BvqC-MDM',
    appId: '1:42806286143:android:eef2f39e51941b42afe58a',
    messagingSenderId: '42806286143',
    projectId: 'coletorgeoforest',
    storageBucket: 'coletorgeoforest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiQgIGS9TLIWWFHMfImE0hxkdjkhE4GmE',
    appId: '1:42806286143:ios:672398aa304927e3afe58a',
    messagingSenderId: '42806286143',
    projectId: 'coletorgeoforest',
    storageBucket: 'coletorgeoforest.firebasestorage.app',
    iosBundleId: 'com.example.geoforestcoletor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiQgIGS9TLIWWFHMfImE0hxkdjkhE4GmE',
    appId: '1:42806286143:ios:672398aa304927e3afe58a',
    messagingSenderId: '42806286143',
    projectId: 'coletorgeoforest',
    storageBucket: 'coletorgeoforest.firebasestorage.app',
    iosBundleId: 'com.example.geoforestcoletor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsg5PMINPmDNg4GYWv9ZS6tckckZBM8so',
    appId: '1:42806286143:web:bb6de0b6df9248e8afe58a',
    messagingSenderId: '42806286143',
    projectId: 'coletorgeoforest',
    authDomain: 'coletorgeoforest.firebaseapp.com',
    storageBucket: 'coletorgeoforest.firebasestorage.app',
    measurementId: 'G-SM14JCBE8W',
  );
}
