// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKcql3CBdM_mTH30V7hyG4bc_Vw4u4QgI',
    appId: '1:1072413984703:web:17877dc6c307cefd28030a',
    messagingSenderId: '1072413984703',
    projectId: 'geoforestfinal',
    authDomain: 'geoforestfinal.firebaseapp.com',
    storageBucket: 'geoforestfinal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDViWoq1UVYf9-ATIO_C0SI__bfvqsQB24',
    appId: '1:1072413984703:android:f796dce25c5cff4b28030a',
    messagingSenderId: '1072413984703',
    projectId: 'geoforestfinal',
    storageBucket: 'geoforestfinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtnEQPoXD6JUFKOvHZCSdyz_grOFDXJfY',
    appId: '1:1072413984703:ios:cbbfb5b769ecf50f28030a',
    messagingSenderId: '1072413984703',
    projectId: 'geoforestfinal',
    storageBucket: 'geoforestfinal.firebasestorage.app',
    iosBundleId: 'com.example.geoforestcoletorv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtnEQPoXD6JUFKOvHZCSdyz_grOFDXJfY',
    appId: '1:1072413984703:ios:cbbfb5b769ecf50f28030a',
    messagingSenderId: '1072413984703',
    projectId: 'geoforestfinal',
    storageBucket: 'geoforestfinal.firebasestorage.app',
    iosBundleId: 'com.example.geoforestcoletorv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKcql3CBdM_mTH30V7hyG4bc_Vw4u4QgI',
    appId: '1:1072413984703:web:9bcf56da7edd0c6428030a',
    messagingSenderId: '1072413984703',
    projectId: 'geoforestfinal',
    authDomain: 'geoforestfinal.firebaseapp.com',
    storageBucket: 'geoforestfinal.firebasestorage.app',
  );

}